# Generated by Django 6.0.2 on 2026-04-13 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cuisine',
            field=models.CharField(choices=[('all', 'All Cuisines'), ('american', 'American'), ('bar', 'Bar'), ('italian', 'Italian'), ('asian', 'Asian'), ('pub', 'Pub'), ('pizza', 'Pizza'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('mexican', 'Mexican'), ('seafood', 'Seafood'), ('sushi', 'Sushi'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('contemporary', 'Contemporary'), ('mediterranean', 'Mediterranean'), ('french', 'French'), ('deli', 'Deli'), ('spanish', 'Spanish'), ('latin', 'Latin'), ('wine_bar', 'Wine Bar'), ('healthy', 'Healthy'), ('european', 'European'), ('scandinavian', 'Scandinavian'), ('indian', 'Indian'), ('thai', 'Thai'), ('korean', 'Korean'), ('middle_eastern', 'Middle Eastern'), ('irish', 'Irish'), ('gastropub', 'Gastropub'), ('caribbean', 'Caribbean'), ('south_american', 'South American'), ('diner', 'Diner'), ('greek', 'Greek'), ('international', 'International'), ('fusion', 'Fusion'), ('barbecue', 'Barbecue'), ('soups', 'Soups'), ('dining_bars', 'Dining Bars'), ('vietnamese', 'Vietnamese'), ('cantonese', 'Cantonese'), ('israeli', 'Israeli'), ('turkish', 'Turkish'), ('grill', 'Grill'), ('lebanese', 'Lebanese'), ('african', 'African'), ('persian', 'Persian'), ('shanghai', 'Shanghai'), ('central_american', 'Central American'), ('japanese_fusion', 'Japanese Fusion'), ('szechuan', 'Szechuan'), ('hong_kong', 'Hong Kong'), ('eastern_european', 'Eastern European'), ('brew_restaurants', 'Brew Restaurants'), ('taiwanese', 'Taiwanese'), ('cuban', 'Cuban'), ('jamaican', 'Jamaican'), ('cajun_creole', 'Cajun & Creole'), ('street_food', 'Street Food'), ('argentinian', 'Argentinian'), ('noodles', 'Noodles'), ('british', 'British'), ('colombian', 'Colombian'), ('hawaiian', 'Hawaiian'), ('malaysian', 'Malaysian'), ('georgian', 'Georgian'), ('southwestern', 'Southwestern'), ('slow_pub', 'Slow Pub'), ('filipino', 'Filipino'), ('central_european', 'Central European'), ('neapolitan', 'Neapolitan'), ('southern_italian', 'Southern Italian'), ('australian', 'Australian'), ('german', 'German'), ('tuscan', 'Tuscan'), ('russian', 'Russian'), ('ethiopian', 'Ethiopian'), ('cosmopolitan', 'Cosmo-Mopolitan'), ('pakistani', 'Pakistani'), ('sicilian', 'Sicilian'), ('moroccan', 'Moroccan'), ('belgian', 'Belgian'), ('austrian', 'Austrian'), ('singapore', 'Singapore'), ('venezuelan', 'Venezuelan'), ('beijing_cuisine', 'Beijing Cuisine'), ('brazilian', 'Brazilian'), ('ukrainian', 'Ukrainian'), ('nepali', 'Nepali'), ('egyptian', 'Egyptian'), ('afghan', 'Afghan'), ('puerto_rican', 'Puerto Rican'), ('arabic', 'Arabic'), ('armenian', 'Armenian'), ('central_italian', 'Central Italian'), ('burmese', 'Burmese'), ('kolkati', 'Kolkati'), ('portuguese', 'Portuguese'), ('other', 'Other')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='occasion',
            field=models.CharField(choices=[('all', 'All Occasions'), ('breakfast_brunch', 'Breakfast / Brunch'), ('date_night', 'Date Night'), ('casual_dining', 'Casual Dining'), ('special_occasions', 'Special Occasions'), ('big_groups', 'Big Groups'), ('drinks_bars', 'Drinks & Bars')], default='all', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section',
            field=models.CharField(choices=[('guides', 'Guides'), ('spotlights', 'Local Spotlights'), ('new_openings', 'New Openings')], default='guides', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subheading',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.blogpost'),
        ),
    ]
