# Generated by Django 6.0.2 on 2026-04-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blogpost_allow_comments_blogpost_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='occasion',
            field=models.CharField(choices=[('date_night', 'Date Night'), ('fine_dining', 'Fine Dining'), ('group_dining', 'Group Dining'), ('quick_bite', 'Quick Bite'), ('Business', 'Business')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='section',
            field=models.CharField(choices=[('guides', 'Guides'), ('reviews', 'Reviews'), ('news', 'News')], default='guides', max_length=50),
        ),
    ]
