# Generated by Django 6.0.2 on 2026-04-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='city',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='occasion',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='section',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='state',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subheading',
        ),
    ]
