# Generated by Django 6.0.2 on 2026-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blogpost_allow_comments_blogpost_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('all', 'All Cuisines'), ('american', 'American'), ('bar', 'Bar'), ('italian', 'Italian'), ('asian', 'Asian'), ('pizza', 'Pizza'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('mexican', 'Mexican'), ('seafood', 'Seafood'), ('sushi', 'Sushi'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('french', 'French'), ('indian', 'Indian'), ('thai', 'Thai'), ('korean', 'Korean'), ('middle_eastern', 'Middle Eastern'), ('greek', 'Greek'), ('fusion', 'Fusion'), ('barbecue', 'Barbecue'), ('vietnamese', 'Vietnamese'), ('turkish', 'Turkish'), ('ethiopian', 'Ethiopian'), ('brazilian', 'Brazilian'), ('german', 'German'), ('british', 'British'), ('other', 'Other')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='occasion',
            field=models.CharField(blank=True, choices=[('date_night', 'Date Night'), ('fine_dining', 'Fine Dining'), ('group_dining', 'Group Dining'), ('quick_bite', 'Quick Bite'), ('business', 'Business')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='section',
            field=models.CharField(blank=True, choices=[('guides', 'Guides'), ('reviews', 'Reviews'), ('news', 'News')], default='guides', max_length=50),
        ),
    ]
