# Generated by Django 6.0.2 on 2026-05-01 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_blogpost_cuisine_alter_blogpost_occasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='vibe',
            field=models.CharField(blank=True, choices=[('cozy', 'Cozy'), ('lively', 'Lively'), ('modern', 'Modern')], default='cozy', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='section',
            field=models.CharField(choices=[('local spotlight', 'Local Spotlight'), ('guides', 'Guides'), ('reviews', 'Reviews'), ('no preference', 'No Preference')], default='guides', max_length=50),
        ),
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
