# Generated by Django 6.0.2 on 2026-05-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contactmessage_contentreport_userreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentReport',
        ),
    ]
